const { contextBridge, ipcRenderer, webUtils } = require('electron');
const filePaths = (files) => files.map((file) => webUtils.getPathForFile(file)).filter(Boolean);

contextBridge.exposeInMainWorld('soundLibrary', {
  getLibrary: () => ipcRenderer.invoke('library:get'),
  addFiles: () => ipcRenderer.invoke('library:add-files'),
  addDroppedFiles: (files) => ipcRenderer.invoke('library:add-paths', filePaths(files)),
  addFolder: () => ipcRenderer.invoke('library:add-folder'),
  openVault: () => ipcRenderer.invoke('vault:open'),
  createVault: () => ipcRenderer.invoke('vault:create'),
  locateVault: () => ipcRenderer.invoke('vault:locate'),
  moveVault: () => ipcRenderer.invoke('vault:move'),
  checkVault: () => ipcRenderer.invoke('vault:check'),
  compactVault: () => ipcRenderer.invoke('vault:compact'),
  revealVault: () => ipcRenderer.invoke('vault:reveal'),
  rescan: () => ipcRenderer.invoke('library:rescan'),
  updateSound: (payload) => ipcRenderer.invoke('library:update', payload),
  renameSound: (payload) => ipcRenderer.invoke('library:rename', payload),
  updateSoundsBatch: (payload) => ipcRenderer.invoke('library:update-batch', payload),
  setTagsBatch: (payload) => ipcRenderer.invoke('library:set-tags-batch', payload),
  moveSoundsToCategory: (payload) => ipcRenderer.invoke('library:move-category-batch', payload),
  removeSoundsBatch: (payload) => ipcRenderer.invoke('library:remove-batch', payload),
  removeSound: (payload) => ipcRenderer.invoke('library:remove', payload),
  moveSoundToFolder: (id) => ipcRenderer.invoke('library:move-folder', id),
  moveSoundToCategory: (payload) => ipcRenderer.invoke('library:move-category', payload),
  createCategoryFolder: (payload) => ipcRenderer.invoke('category:create', payload),
  renameCategoryFolder: (payload) => ipcRenderer.invoke('category:rename', payload),
  moveCategoryUp: (category) => ipcRenderer.invoke('category:move-up', category),
  reorderCategories: (payload) => ipcRenderer.invoke('category:reorder', payload),
  trashCategoryFolder: (category) => ipcRenderer.invoke('category:trash', category),
  trashCategoryFolders: (categories) => ipcRenderer.invoke('category:trash-batch', categories),
  revealCategoryFolder: (category) => ipcRenderer.invoke('category:reveal', category),
  addFilesToCategory: (category) => ipcRenderer.invoke('category:add-files', category),
  dropFilesToCategory: (category, files) => ipcRenderer.invoke('category:drop-paths', { category, paths: filePaths(files) }),
  startCategoryDrag: (category) => ipcRenderer.send('category:start-drag', category),
  setShortcuts: (shortcuts) => ipcRenderer.invoke('shortcuts:set', shortcuts),
  setPreviewVolume: (volume) => ipcRenderer.invoke('preview-volume:set', volume),
  getUpdateStatus: () => ipcRenderer.invoke('update:status'),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  openUpdatePage: () => ipcRenderer.invoke('update:open-release'),
  exportBackup: () => ipcRenderer.invoke('library:backup-export'),
  importBackup: () => ipcRenderer.invoke('library:backup-import'),
  collectMetadata: () => ipcRenderer.invoke('library:collect-metadata'),
  findDuplicates: () => ipcRenderer.invoke('library:find-duplicates'),
  relinkMissing: () => ipcRenderer.invoke('library:relink-missing'),
  relinkOne: (id) => ipcRenderer.invoke('library:relink-one', id),
  setShortcutCapture: (active) => ipcRenderer.send('shortcuts:capture', active),
  getWaveform: (id) => ipcRenderer.invoke('library:waveform', id),
  analyzeKey: (payload) => ipcRenderer.invoke('library:analyze-key', payload),
  prepareClip: (payload) => ipcRenderer.invoke('library:prepare-clip', payload),
  createClip: (payload) => ipcRenderer.invoke('library:create-clip', payload),
  reveal: (filePath) => ipcRenderer.invoke('library:reveal', filePath),
  insertIntoResolve: (sound) => ipcRenderer.invoke('resolve:insert', sound),
  startDrag: (filePath) => ipcRenderer.send('library:start-drag', filePath),
  onDragError: (callback) => ipcRenderer.on('drag-error', (_event, message) => callback(message)),
  onScanProgress: (callback) => ipcRenderer.on('scan-progress', (_event, payload) => callback(payload)),
  onLibraryUpdated: (callback) => ipcRenderer.on('library-updated', (_event, snapshot) => callback(snapshot)),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (_event, status) => callback(status)),
  onShortcut: (callback) => ipcRenderer.on('shortcut-triggered', (_event, shortcut) => callback(shortcut))
});
